#!/bin/bash

cd /tmp

cur=$(pwd)
# First load the repo Gnublin
git clone http://code.google.com/p/gnublin/

if [ ! -d "$cur/gnublin/lpc3131/Downloads" ]
then 
	mkdir $cur/gnublin/lpc3131/Downloads
fi

cd $cur/gnublin/lpc3131/Downloads
# Load Kernel repo
git clone http://code.google.com/p/gnublin-develop-kernel/

#mv gnublin-develop-kernel/linux-2.6.33-lpc313x kernel/
#rm -r gnublin-develop-kernel
 
# delete everything what has to do with git

cd $cur 


find /tmp/gnublin -name ".git" -exec rm -r {} \; 

cd $cur/gnublin/lpc3131/
rm $cur/gnublin/lpc3131/get_gnublin_distro_src
$cur/gnublin/lpc3131/build_GNUBLIN_support_package.sh
tar zc -f /tmp/gnublin_distro_complete.tar.gz *


 
