
# ELDK-5.0
CC = arm-none-linux-gnueabi-gcc

INCLDIR = /opt/eldk-5.0/armv5te/sysroots/arm-linux-gnueabi/usr/include

spidev_test_merkle:
	$(CC) -g -I$(INCLDIR) -o spidev_test_2 spidev_test_2.c

clean:
		rm -f spidev_test_2 *~
