#!/bin/bash

if [ "$1" = "" ]
then
	packages="*"
else
	packages="$1"
fi
	


for i in $packages ; do

	if [ "$i" = "README"  ] || [ "$i" = "mkdeb_package"  ] || [ "${i:0:6}" = "NODEB_"  ]
	then
	continue
	fi
chmod -R 0755 $i  

if [ ! -d "../deb" ]
then 
	mkdir ../deb/
fi

dpkg -b $i ../deb/${i}.deb

done
