all:
	gcc -Wall -g -loctopus -o led led.c -lusb

win:
	gcc -c ../../liboctopus/src/octopus.c -I c:\Programme\LibUSB-Win32\include
	gcc -o demo.exe octopus.o demo.c -lusb -I c:\Programme\LibUSB-Win32\include -L c:\Programme\LibUSB-Win32\lib\gcc -I ../../liboctopus/src


clean:
	rm -f led

