#! /bin/bash


module="0"
pin="0"
inputf="0"
brutef=""
output_val=""
json_f=""
brutef=""
helpstring='This program was designed to easily interact with the relay module for GNUBLIN.

-h show this help    
-m <X> specify the relay-module number(0-7)(default=0)    
-p <Y> specify the relay number (0-7)    
-o <value> set pin as output with given <value>(0= low / 1 = high)    
-i set pin as input and read the value   
-l list all relay-modules connected to GNUBLIN    
-j show output in json format    
-b show output in raw format                

Examples:    
Set relay 0 on module 0 high   
gnublin-relais -m 0 -p 0 -o 1      

Set pin 0 of module 0 low   
gnublin-relais -m 0 -p 0 -o 0      
     
Set pin 0 of module 1 high   
gnublin-relais -m 1 -p 0 -o 1   

Read the value of relay 3 on module 0
gnublin-relais -p 3 -i
'


while getopts p:jhio:fb opt
 do
      case $opt in
          p) pin="${OPTARG}" ;;
          i) inputf="1" ;;
          o) output_val="${OPTARG}" ;;
	  j) json_f="1" ;;
	  f) freef="1" ;;
	  b) brutef="1" ;;
          ?) echo "$helpstring"
             exit 1 ;;
          h) echo "$helpstring"
             exit 1 ;;
      esac
done


#make sure that you only use pins which are avialable
if [ "$pin" -gt "7" ]
then
      if [ "$json_f" == "1" ]
      then
      echo "{ \"error_msg\" : \"Invalid relay selected.\",\"result\" : \"-1\" }"
      else
      echo "Invalid relay pin selected. Only 0-7 available on the relay-module"
      fi
      exit 1
fi

#check if pin is an integer
if [ "${pin//[0-9]*}" != "" ] 
then
		if [ "$json_f" == "1" ]
		then
			echo "{ \"error_msg\" : \"Only Integers allowed as relay number\",\"result\" : \"-2\" }"
		else
		echo "Only Integers allowed as relay number"
		fi
   exit 1
fi


#Now set/read the gpio value
if [ "$inputf" == "1" ]
then
        #read the input
  if [ "$json_f" == "1" ]
  then
  /usr/bin/gnublin-pca9555 -p $pin -i -j
  else 
  /usr/bin/gnublin-pca9555 -p $pin -i
  fi


elif [ -n "$output_val" ]
then

      #set the output

        if [ "$json_f" == "1" ]
        then
	/usr/bin/gnublin-pca9555 -p $pin -o $output_val -j
        else
	/usr/bin/gnublin-pca9555 -p $pin -o $output_val
        fi

      exit 0
fi